INSERT INTO CADOC_ADMIN.STOCK (NOM_S, LIEU, DATE_R) VALUES ('Depot', 'Bouchaoui', null);
INSERT INTO CADOC_ADMIN.STOCK (NOM_S, LIEU, DATE_R) VALUES ('Reserve A', 'Delly Ibrahim', null);
INSERT INTO CADOC_ADMIN.STOCK (NOM_S, LIEU, DATE_R) VALUES ('Reserve B', 'Delly Ibrahim', null);
INSERT INTO CADOC_ADMIN.STOCK (NOM_S, LIEU, DATE_R) VALUES ('Reserve C', 'Delly Ibrahim', null);
INSERT INTO CADOC_ADMIN.STOCK (NOM_S, LIEU, DATE_R) VALUES ('Librairie', 'Delly Ibrahim', null);
INSERT INTO CADOC_ADMIN.STOCK (NOM_S, LIEU, DATE_R) VALUES ('ST1', 'Alger ', '12-03-2005 ');
INSERT INTO CADOC_ADMIN.STOCK (NOM_S, LIEU, DATE_R) VALUES ('NVStock', 'Alger ', '08-09-2018 ');